### ISSUE TITLE
Java 19 incompatible with Minecraft 1.8.9

### ISSUE THREAD

**Issue by GrizzlT** [Ninlives/minecraft.nix#18]
I came across this project today and it is looking quite neat!

When I tried to run the 1.8.9 version, the resulting program crashes every time I try to join hypixel.net (haven't checked other servers) with an error saying it can't access address of the buffer.

I managed to fix the issue by replacing the `jre` package in the `module/client.nix` file by the `jre8` package. Apparently java 19 is too new? Could anyone provide insight in this?

**Comment by Ninlives** [comment]
I am not playing minecraft recently, @linyinfeng can you reproduce this issue?

**Comment by linyinfeng** [comment]
> I am not playing minecraft recently, @linyinfeng can you reproduce this issue?

I can reproduce this issue on my laptop. And the official FAQ of Minecraft Java edition (<https://help.minecraft.net/hc/en-us/articles/4409225939853-Minecraft-Java-Edition-Installation-Issues-FAQ>) does mention Java version requirements:

> Java 8 is required to run Minecraft versions 1.12 through 1.17. Java 17 is required to run Minecraft version 1.18 and up. 

I opened PR https://github.com/Ninlives/minecraft.nix/pull/19 to implement this requirement.
